"""Stone resource node: a jagged low-poly rock outcrop.

Run inside Blender (Text Editor > Run Script, or exec() over the MCP bridge).
It builds or rebuilds the `StoneNode` object and writes `stone_node.obj` and
`stone_node.mtl` next to this file. The seed is fixed, so the output is the
same on every run.

1 Blender unit = 1 stud. The base sits on z=0, and the peak is TARGET_H studs
tall (waist-to-shoulder on a 5-stud avatar). Blender is Z-up; the OBJ is
written Y-up so it imports into Roblox upright.
"""

import math
import os
import random

import bmesh
import bpy
from mathutils import Vector

SEED = 1337
TARGET_H = 3.3
COLOR = (0.62, 0.63, 0.65)
NAME = "StoneNode"


def build_stone(seed=SEED):
    random.seed(seed)
    bm = bmesh.new()
    bmesh.ops.create_icosphere(bm, subdivisions=2, radius=1.0)

    # 1. Strong radial + tangential jitter
    for v in bm.verts:
        d = v.co.normalized()
        r = 1.0 + random.uniform(-0.3, 0.35)
        j = Vector([random.uniform(-0.2, 0.2) for _ in range(3)])
        v.co = d * r + j

    # 2. Squash low and squat, wide footprint
    for v in bm.verts:
        v.co.x *= 3.0; v.co.y *= 2.3; v.co.z *= 1.2

    # 3. Steep side cleaves -> cliff faces
    for k in range(6):
        th = k * (2 * math.pi / 6) + random.uniform(-0.4, 0.4)
        tilt = random.uniform(math.radians(55), math.radians(85))
        n = Vector((math.cos(th) * math.sin(tilt), math.sin(th) * math.sin(tilt), math.cos(tilt)))
        extent = max(v.co.dot(n) for v in bm.verts)
        offset = extent * random.uniform(0.72, 0.86)
        for v in bm.verts:
            over = v.co.dot(n) - offset
            if over > 0:
                v.co -= n * over

    # 4. Gentle shear: one end rises out of the ground
    for v in bm.verts:
        v.co.z += 0.14 * (v.co.x + 3.0) * max(0.0, v.co.z + 0.5) / 2.0

    # 5. Crown broken into several smaller peaks, spread along the top
    tops = sorted(bm.verts, key=lambda v: -v.co.z)[:12]
    peaks = []
    for v in tops:  # pick peaks at least 1.2 studs apart horizontally
        if all((v.co.xy - p.co.xy).length > 1.2 for p in peaks):
            peaks.append(v)
        if len(peaks) == 3:
            break
    for pv, lift in zip(peaks, (0.6, 0.45, 0.3)):
        pv.co.z += lift
    for v in tops:  # notch the ridge between peaks
        if v not in peaks:
            v.co.z -= 0.2

    # 6. Flat base on ground, then normalize height
    minz = min(v.co.z for v in bm.verts)
    floor = minz + 0.5
    for v in bm.verts:
        if v.co.z < floor:
            v.co.z = floor
        v.co.z -= floor
    h = max(v.co.z for v in bm.verts)
    for v in bm.verts:
        v.co.z *= TARGET_H / h

    bmesh.ops.triangulate(bm, faces=bm.faces)
    return bm


def build_object():
    mat = bpy.data.materials.get(NAME + "_Mat")
    if mat is None:
        mat = bpy.data.materials.new(NAME + "_Mat")
        mat.use_nodes = True
        bsdf = next(n for n in mat.node_tree.nodes if n.type == "BSDF_PRINCIPLED")
        bsdf.inputs["Base Color"].default_value = (*COLOR, 1.0)
        bsdf.inputs["Roughness"].default_value = 0.9
        mat.diffuse_color = (*COLOR, 1.0)

    mesh = bpy.data.meshes.new(NAME + "_tmp")
    bm = build_stone()
    bm.to_mesh(mesh)
    bm.free()
    for p in mesh.polygons:
        p.use_smooth = False  # hard-edged facets
    mesh.materials.append(mat)

    obj = bpy.data.objects.get(NAME)
    if obj is None:
        obj = bpy.data.objects.new(NAME, mesh)
        bpy.context.scene.collection.objects.link(obj)
    else:
        old = obj.data
        obj.data = mesh
        if old.users == 0:
            bpy.data.meshes.remove(old)
    mesh.name = NAME
    return obj


def write_obj(mesh, directory):
    """Flat-shaded OBJ, one normal per face, converted from Z-up to Y-up."""
    def yup(c):
        return (c.x, c.z, -c.y)

    obj_path = os.path.join(directory, "stone_node.obj")
    mtl_path = os.path.join(directory, "stone_node.mtl")
    with open(mtl_path, "w", newline="\n") as f:
        f.write("newmtl StoneNode_Mat\n")
        f.write("Kd %.4f %.4f %.4f\n" % COLOR)
        f.write("Ka 0 0 0\nKs 0 0 0\nd 1\nillum 1\n")
    with open(obj_path, "w", newline="\n") as f:
        f.write("# Stone resource node, generated by build_stone_node.py (seed %d)\n" % SEED)
        f.write("mtllib stone_node.mtl\no StoneNode\n")
        for v in mesh.vertices:
            f.write("v %.5f %.5f %.5f\n" % yup(v.co))
        for p in mesh.polygons:
            f.write("vn %.5f %.5f %.5f\n" % yup(p.normal))
        f.write("usemtl StoneNode_Mat\ns off\n")
        for i, p in enumerate(mesh.polygons, start=1):
            f.write("f " + " ".join("%d//%d" % (vi + 1, i) for vi in p.vertices) + "\n")
    return obj_path


def main(out_dir=None):
    out_dir = out_dir or os.path.dirname(os.path.abspath(__file__))
    obj = build_object()
    path = write_obj(obj.data, out_dir)
    tris = sum(len(p.vertices) - 2 for p in obj.data.polygons)
    print("StoneNode: %d tris, dims %s -> %s" % (tris, tuple(round(d, 2) for d in obj.dimensions), path))
    return obj


if __name__ == "__main__":
    main()
